server:
  # 端口号
  port: 8084
  #  请求前缀
  path:
  version: 1.1.0

postgresql:
  host: localhost
  # host: 192.168.5.5
  port: 5432
  user: postgres
  password: 123456
  db-name: ry_to_go


redis:
  address: localhost:6379
  password: 123456
  db: 0

cache:
  # 验证码缓存
  captcha:
    prefix: "captcha:login:"
    expiration: 30m
  # 用户信息缓存
  login:
    prefix: "user:login:"
    expiration: 60m
  # 请求令牌缓存
  auth:
    prefix: "request:auth:"
    expiration: 60m

jwt:
  secret: testjwtsecretadmin
  duration: 30m
  resp-header-key: Authorization
  auth-prefix: Bearer

rsa:
  key:
    public: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvuXS32dkE6Aal64py+Vo
      B37HC2NPTv+0LBVorgZ1sYKsXE3KbEabs53UDRSxwqxhnnXgf6x39Je2c4P0o6iG
      U3Qocn6OSHcckaltFsFT6OzYuPybk374eZX2mZT4ErWm/a0N60bC1Id0qFlraLGU
      EiR3B/hancVf/DZVEyZiFv1/OHRllOdoETJFeIYoogrhfNWYXanvgxPwXYL6jttr
      dL5TLrlfFz+zXqW+1hPE7qVu8Po02Jfh5l4NwHsYid4gtznbYZ7DfCz27rUj/4Qw
      z9c2NjI7AQmY8ESyR5nFpK1KIoH/UuV0AuZsGvpHIq/9dBJqECO7U3SggX7mmZwh
      4wIDAQAB
      -----END PUBLIC KEY-----
    private: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEAvuXS32dkE6Aal64py+VoB37HC2NPTv+0LBVorgZ1sYKsXE3K
      bEabs53UDRSxwqxhnnXgf6x39Je2c4P0o6iGU3Qocn6OSHcckaltFsFT6OzYuPyb
      k374eZX2mZT4ErWm/a0N60bC1Id0qFlraLGUEiR3B/hancVf/DZVEyZiFv1/OHRl
      lOdoETJFeIYoogrhfNWYXanvgxPwXYL6jttrdL5TLrlfFz+zXqW+1hPE7qVu8Po0
      2Jfh5l4NwHsYid4gtznbYZ7DfCz27rUj/4Qwz9c2NjI7AQmY8ESyR5nFpK1KIoH/
      UuV0AuZsGvpHIq/9dBJqECO7U3SggX7mmZwh4wIDAQABAoIBAGONNNAeefkmGFgb
      kl5rjznBaonMy3I2NT58F7ARXFUrATnNs4+NrusXlpsPvLf575qUfHP4fEII0DQj
      j3O9kfd5bxJuX0L5IuPviB1CysCAq3ClA3kC0Q+PHh/vqQMQyjomgki9CSOOVE7q
      +vGJEd/4Nj7ozFDUun6r0uf+r06vE1xK5qe9neOdPNHZtN/vyhGAWzeulrUB9hix
      ytwgoiG6jK5tw2kPzDJlslKtkueH2B0dJZ+Y05uGHbG7BpH3EG0CgYOy3Vr5JQhS
      oBHwYjQ6W4V+/7aCHkZUODEeLyTHPP3Ed+lBw1/meFNp+VxL2HM/7uNGuWu1QkMT
      y07eXEkCgYEA5uaYib1GVC3qSd1aashNLJFV0zfVWRWDPlPFOXC9KlY3gNYcf4xm
      QE81N0MMbVIn0GNSDmPj36bOi9w6nmaSpLp3rOOoiElzv5eaEpaBMJJ9/zWX4LYL
      TFXTfnnBBCgawIadSbbWddBOyMTOjFhsQGPelMzavMqODg5Y5YybEj8CgYEA06YK
      qrFfpOh2rq3Lq+vRZDk1gTWbUB5TmlNyoPoT/ZU6zGBemV2wKQvI+JZCALi/FphX
      /V9zELmBs28zgkmahTFIJrr9rSLXDtYIjmYI3WeVL1z8YNQKD5FpnFSRCHk8fzCT
      IjkD5RmJvdqCX3zEZ0CaSTSXgteer89Jo//3P10CgYEA2ZGlX/x6XW2aWxl5Ti8J
      ERqtDUaKANQVg9A5gcNqa48r43ldBw6LdsNr+HN0LTqBi4la03ZqTN6Htx/AGGu8
      d/3AMKefsTPNHlZCdotcliEjGiwsvS+r+7TPgVhGeJ01f/4YDVJ8SC0NX36axYG4
      FwBDxmA1KDmQm0wHldzkbc8CgYA+K5EIkO/KbiqmpxCj4LJyYUexO8DyqOXf+FE8
      rhj/LT3HWSuQm2+qrvaK5wBeW+ZtybRXDhmruQI7ZhfYVqyYIWDTV6w6lnhbuE1t
      HtXNy6aL8iGEg+SsrAc8z66Gsa4uomMl81+MhZLrfOs9B1ZeCiEIDfXPjmzjsd0s
      2nyTVQKBgBNsik6R/a6QIWwcBB3asoI8N92BEp+iXtGhmPITZ9aAQ1p8qfMZZ0tQ
      JMTFE8Ua9hY6MEv7MXyYLyACrEZlgmvZJCMoll/X3Q7p/qNjtYODnmeN0W6EI5bh
      LZjftcNtkcemxrRze5EXHF4drFOL0gMclf26AyZmYZgB35f6cBD7
      -----END RSA PRIVATE KEY-----


request:
  # 请求白名单
  white-url:
    - /user/test/aaaaa
    - /user/test
    - /system/dept/check/exist
    - /system/dept/save
    - /system/dept/batchSave
    - /system/dept/batchSaveList
    - /system/dept/update
    - /system/dept/import
    - /system/dept/page
    - /system/dept/batchDelete
    - /template/data
    - /system/notice/save
    - /system/notice/batchSave
    - /system/notice/update
    - /system/notice/page
    - /system/notice/
    - /system/notice/batchDelete
    - /system/menu/
    - /system/user/login
    - /system/user/captcha/redis
    - /system/user/captcha/redis/verify
    - /system/file/
    - /barcode/generate
    - /qrcode/generate
    - /system/role
    - /captchaImage
    - /login